# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.10
#
# <auto-generated>
#
# Generated from file `ICE_LogApplication.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module UVLogAppServer
_M_UVLogAppServer = Ice.openModule('UVLogAppServer')
__name__ = 'UVLogAppServer'

_M_UVLogAppServer._t_LogAppServer = IcePy.defineValue('::UVLogAppServer::LogAppServer', Ice.Value, -1, (), False, True, None, ())

if 'LogAppServerPrx' not in _M_UVLogAppServer.__dict__:
    _M_UVLogAppServer.LogAppServerPrx = Ice.createTempClass()
    class LogAppServerPrx(Ice.ObjectPrx):

        def Ping(self, context=None):
            return _M_UVLogAppServer.LogAppServer._op_Ping.invoke(self, ((), context))

        def PingAsync(self, context=None):
            return _M_UVLogAppServer.LogAppServer._op_Ping.invokeAsync(self, ((), context))

        def begin_Ping(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_UVLogAppServer.LogAppServer._op_Ping.begin(self, ((), _response, _ex, _sent, context))

        def end_Ping(self, _r):
            return _M_UVLogAppServer.LogAppServer._op_Ping.end(self, _r)

        def Shutdown(self, context=None):
            return _M_UVLogAppServer.LogAppServer._op_Shutdown.invoke(self, ((), context))

        def ShutdownAsync(self, context=None):
            return _M_UVLogAppServer.LogAppServer._op_Shutdown.invokeAsync(self, ((), context))

        def begin_Shutdown(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_UVLogAppServer.LogAppServer._op_Shutdown.begin(self, ((), _response, _ex, _sent, context))

        def end_Shutdown(self, _r):
            return _M_UVLogAppServer.LogAppServer._op_Shutdown.end(self, _r)

        def insertItem(self, paLogNumber, paComputerName, paApplicationName, paApplicationText, context=None):
            return _M_UVLogAppServer.LogAppServer._op_insertItem.invoke(self, ((paLogNumber, paComputerName, paApplicationName, paApplicationText), context))

        def insertItemAsync(self, paLogNumber, paComputerName, paApplicationName, paApplicationText, context=None):
            return _M_UVLogAppServer.LogAppServer._op_insertItem.invokeAsync(self, ((paLogNumber, paComputerName, paApplicationName, paApplicationText), context))

        def begin_insertItem(self, paLogNumber, paComputerName, paApplicationName, paApplicationText, _response=None, _ex=None, _sent=None, context=None):
            return _M_UVLogAppServer.LogAppServer._op_insertItem.begin(self, ((paLogNumber, paComputerName, paApplicationName, paApplicationText), _response, _ex, _sent, context))

        def end_insertItem(self, _r):
            return _M_UVLogAppServer.LogAppServer._op_insertItem.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_UVLogAppServer.LogAppServerPrx.ice_checkedCast(proxy, '::UVLogAppServer::LogAppServer', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_UVLogAppServer.LogAppServerPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::UVLogAppServer::LogAppServer'
    _M_UVLogAppServer._t_LogAppServerPrx = IcePy.defineProxy('::UVLogAppServer::LogAppServer', LogAppServerPrx)

    _M_UVLogAppServer.LogAppServerPrx = LogAppServerPrx
    del LogAppServerPrx

    _M_UVLogAppServer.LogAppServer = Ice.createTempClass()
    class LogAppServer(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::UVLogAppServer::LogAppServer')

        def ice_id(self, current=None):
            return '::UVLogAppServer::LogAppServer'

        @staticmethod
        def ice_staticId():
            return '::UVLogAppServer::LogAppServer'

        def Ping(self, current=None):
            raise NotImplementedError("servant method 'Ping' not implemented")

        def Shutdown(self, current=None):
            raise NotImplementedError("servant method 'Shutdown' not implemented")

        def insertItem(self, paLogNumber, paComputerName, paApplicationName, paApplicationText, current=None):
            raise NotImplementedError("servant method 'insertItem' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_UVLogAppServer._t_LogAppServerDisp)

        __repr__ = __str__

    _M_UVLogAppServer._t_LogAppServerDisp = IcePy.defineClass('::UVLogAppServer::LogAppServer', LogAppServer, (), None, ())
    LogAppServer._ice_type = _M_UVLogAppServer._t_LogAppServerDisp

    LogAppServer._op_Ping = IcePy.Operation('Ping', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), ((), IcePy._t_bool, False, 0), ())
    LogAppServer._op_Shutdown = IcePy.Operation('Shutdown', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), None, ())
    LogAppServer._op_insertItem = IcePy.Operation('insertItem', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0)), (), None, ())

    _M_UVLogAppServer.LogAppServer = LogAppServer
    del LogAppServer

# End of module UVLogAppServer
