# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.10
#
# <auto-generated>
#
# Generated from file `ICE_ServerApplication.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module UVServerAppServer
_M_UVServerAppServer = Ice.openModule('UVServerAppServer')
__name__ = 'UVServerAppServer'

if '_t_tyStringSequence' not in _M_UVServerAppServer.__dict__:
    _M_UVServerAppServer._t_tyStringSequence = IcePy.defineSequence('::UVServerAppServer::tyStringSequence', (), IcePy._t_string)

_M_UVServerAppServer._t_ServerAppServer = IcePy.defineValue('::UVServerAppServer::ServerAppServer', Ice.Value, -1, (), False, True, None, ())

if 'ServerAppServerPrx' not in _M_UVServerAppServer.__dict__:
    _M_UVServerAppServer.ServerAppServerPrx = Ice.createTempClass()
    class ServerAppServerPrx(Ice.ObjectPrx):

        def Ping(self, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_Ping.invoke(self, ((), context))

        def PingAsync(self, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_Ping.invokeAsync(self, ((), context))

        def begin_Ping(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_Ping.begin(self, ((), _response, _ex, _sent, context))

        def end_Ping(self, _r):
            return _M_UVServerAppServer.ServerAppServer._op_Ping.end(self, _r)

        def Shutdown(self, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_Shutdown.invoke(self, ((), context))

        def ShutdownAsync(self, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_Shutdown.invokeAsync(self, ((), context))

        def begin_Shutdown(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_Shutdown.begin(self, ((), _response, _ex, _sent, context))

        def end_Shutdown(self, _r):
            return _M_UVServerAppServer.ServerAppServer._op_Shutdown.end(self, _r)

        def insertIntoTableDatabase(self, paTableName, paColumns, paValue, paTypeValue, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_insertIntoTableDatabase.invoke(self, ((paTableName, paColumns, paValue, paTypeValue), context))

        def insertIntoTableDatabaseAsync(self, paTableName, paColumns, paValue, paTypeValue, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_insertIntoTableDatabase.invokeAsync(self, ((paTableName, paColumns, paValue, paTypeValue), context))

        def begin_insertIntoTableDatabase(self, paTableName, paColumns, paValue, paTypeValue, _response=None, _ex=None, _sent=None, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_insertIntoTableDatabase.begin(self, ((paTableName, paColumns, paValue, paTypeValue), _response, _ex, _sent, context))

        def end_insertIntoTableDatabase(self, _r):
            return _M_UVServerAppServer.ServerAppServer._op_insertIntoTableDatabase.end(self, _r)

        def updateIntoTableDatabase(self, paTableName, paId, paColumns, paValue, paTypeValue, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_updateIntoTableDatabase.invoke(self, ((paTableName, paId, paColumns, paValue, paTypeValue), context))

        def updateIntoTableDatabaseAsync(self, paTableName, paId, paColumns, paValue, paTypeValue, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_updateIntoTableDatabase.invokeAsync(self, ((paTableName, paId, paColumns, paValue, paTypeValue), context))

        def begin_updateIntoTableDatabase(self, paTableName, paId, paColumns, paValue, paTypeValue, _response=None, _ex=None, _sent=None, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_updateIntoTableDatabase.begin(self, ((paTableName, paId, paColumns, paValue, paTypeValue), _response, _ex, _sent, context))

        def end_updateIntoTableDatabase(self, _r):
            return _M_UVServerAppServer.ServerAppServer._op_updateIntoTableDatabase.end(self, _r)

        def deleteIntoTableDatabase(self, paTableName, paId, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_deleteIntoTableDatabase.invoke(self, ((paTableName, paId), context))

        def deleteIntoTableDatabaseAsync(self, paTableName, paId, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_deleteIntoTableDatabase.invokeAsync(self, ((paTableName, paId), context))

        def begin_deleteIntoTableDatabase(self, paTableName, paId, _response=None, _ex=None, _sent=None, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_deleteIntoTableDatabase.begin(self, ((paTableName, paId), _response, _ex, _sent, context))

        def end_deleteIntoTableDatabase(self, _r):
            return _M_UVServerAppServer.ServerAppServer._op_deleteIntoTableDatabase.end(self, _r)

        def getFromTableDatabaseGeneral(self, paTableName, paStartValue, paMaxValue, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_getFromTableDatabaseGeneral.invoke(self, ((paTableName, paStartValue, paMaxValue), context))

        def getFromTableDatabaseGeneralAsync(self, paTableName, paStartValue, paMaxValue, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_getFromTableDatabaseGeneral.invokeAsync(self, ((paTableName, paStartValue, paMaxValue), context))

        def begin_getFromTableDatabaseGeneral(self, paTableName, paStartValue, paMaxValue, _response=None, _ex=None, _sent=None, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_getFromTableDatabaseGeneral.begin(self, ((paTableName, paStartValue, paMaxValue), _response, _ex, _sent, context))

        def end_getFromTableDatabaseGeneral(self, _r):
            return _M_UVServerAppServer.ServerAppServer._op_getFromTableDatabaseGeneral.end(self, _r)

        def getFromTableDatbaseByProperty(self, paTableName, paStartValue, paMaxValue, paProperties, paValue, paTypeValue, paLogExp, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_getFromTableDatbaseByProperty.invoke(self, ((paTableName, paStartValue, paMaxValue, paProperties, paValue, paTypeValue, paLogExp), context))

        def getFromTableDatbaseByPropertyAsync(self, paTableName, paStartValue, paMaxValue, paProperties, paValue, paTypeValue, paLogExp, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_getFromTableDatbaseByProperty.invokeAsync(self, ((paTableName, paStartValue, paMaxValue, paProperties, paValue, paTypeValue, paLogExp), context))

        def begin_getFromTableDatbaseByProperty(self, paTableName, paStartValue, paMaxValue, paProperties, paValue, paTypeValue, paLogExp, _response=None, _ex=None, _sent=None, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_getFromTableDatbaseByProperty.begin(self, ((paTableName, paStartValue, paMaxValue, paProperties, paValue, paTypeValue, paLogExp), _response, _ex, _sent, context))

        def end_getFromTableDatbaseByProperty(self, _r):
            return _M_UVServerAppServer.ServerAppServer._op_getFromTableDatbaseByProperty.end(self, _r)

        def getFromTableDatabaseById(self, paTableName, paId, paProperties, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_getFromTableDatabaseById.invoke(self, ((paTableName, paId, paProperties), context))

        def getFromTableDatabaseByIdAsync(self, paTableName, paId, paProperties, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_getFromTableDatabaseById.invokeAsync(self, ((paTableName, paId, paProperties), context))

        def begin_getFromTableDatabaseById(self, paTableName, paId, paProperties, _response=None, _ex=None, _sent=None, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_getFromTableDatabaseById.begin(self, ((paTableName, paId, paProperties), _response, _ex, _sent, context))

        def end_getFromTableDatabaseById(self, _r):
            return _M_UVServerAppServer.ServerAppServer._op_getFromTableDatabaseById.end(self, _r)

        def getAllTablesFromDatabase(self, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_getAllTablesFromDatabase.invoke(self, ((), context))

        def getAllTablesFromDatabaseAsync(self, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_getAllTablesFromDatabase.invokeAsync(self, ((), context))

        def begin_getAllTablesFromDatabase(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_getAllTablesFromDatabase.begin(self, ((), _response, _ex, _sent, context))

        def end_getAllTablesFromDatabase(self, _r):
            return _M_UVServerAppServer.ServerAppServer._op_getAllTablesFromDatabase.end(self, _r)

        def getAllMethodsFromTable(self, paTable, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_getAllMethodsFromTable.invoke(self, ((paTable, ), context))

        def getAllMethodsFromTableAsync(self, paTable, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_getAllMethodsFromTable.invokeAsync(self, ((paTable, ), context))

        def begin_getAllMethodsFromTable(self, paTable, _response=None, _ex=None, _sent=None, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_getAllMethodsFromTable.begin(self, ((paTable, ), _response, _ex, _sent, context))

        def end_getAllMethodsFromTable(self, _r):
            return _M_UVServerAppServer.ServerAppServer._op_getAllMethodsFromTable.end(self, _r)

        def getAllPropertiesFromTable(self, paTable, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_getAllPropertiesFromTable.invoke(self, ((paTable, ), context))

        def getAllPropertiesFromTableAsync(self, paTable, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_getAllPropertiesFromTable.invokeAsync(self, ((paTable, ), context))

        def begin_getAllPropertiesFromTable(self, paTable, _response=None, _ex=None, _sent=None, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_getAllPropertiesFromTable.begin(self, ((paTable, ), _response, _ex, _sent, context))

        def end_getAllPropertiesFromTable(self, _r):
            return _M_UVServerAppServer.ServerAppServer._op_getAllPropertiesFromTable.end(self, _r)

        def giveWorkstationClientInfo(self, paWorkstationName, paPercentageMemUsage, paPercentageDiskUsage, paPercentageCpuUsage, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_giveWorkstationClientInfo.invoke(self, ((paWorkstationName, paPercentageMemUsage, paPercentageDiskUsage, paPercentageCpuUsage), context))

        def giveWorkstationClientInfoAsync(self, paWorkstationName, paPercentageMemUsage, paPercentageDiskUsage, paPercentageCpuUsage, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_giveWorkstationClientInfo.invokeAsync(self, ((paWorkstationName, paPercentageMemUsage, paPercentageDiskUsage, paPercentageCpuUsage), context))

        def begin_giveWorkstationClientInfo(self, paWorkstationName, paPercentageMemUsage, paPercentageDiskUsage, paPercentageCpuUsage, _response=None, _ex=None, _sent=None, context=None):
            return _M_UVServerAppServer.ServerAppServer._op_giveWorkstationClientInfo.begin(self, ((paWorkstationName, paPercentageMemUsage, paPercentageDiskUsage, paPercentageCpuUsage), _response, _ex, _sent, context))

        def end_giveWorkstationClientInfo(self, _r):
            return _M_UVServerAppServer.ServerAppServer._op_giveWorkstationClientInfo.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_UVServerAppServer.ServerAppServerPrx.ice_checkedCast(proxy, '::UVServerAppServer::ServerAppServer', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_UVServerAppServer.ServerAppServerPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::UVServerAppServer::ServerAppServer'
    _M_UVServerAppServer._t_ServerAppServerPrx = IcePy.defineProxy('::UVServerAppServer::ServerAppServer', ServerAppServerPrx)

    _M_UVServerAppServer.ServerAppServerPrx = ServerAppServerPrx
    del ServerAppServerPrx

    _M_UVServerAppServer.ServerAppServer = Ice.createTempClass()
    class ServerAppServer(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::UVServerAppServer::ServerAppServer')

        def ice_id(self, current=None):
            return '::UVServerAppServer::ServerAppServer'

        @staticmethod
        def ice_staticId():
            return '::UVServerAppServer::ServerAppServer'

        def Ping(self, current=None):
            raise NotImplementedError("servant method 'Ping' not implemented")

        def Shutdown(self, current=None):
            raise NotImplementedError("servant method 'Shutdown' not implemented")

        def insertIntoTableDatabase(self, paTableName, paColumns, paValue, paTypeValue, current=None):
            raise NotImplementedError("servant method 'insertIntoTableDatabase' not implemented")

        def updateIntoTableDatabase(self, paTableName, paId, paColumns, paValue, paTypeValue, current=None):
            raise NotImplementedError("servant method 'updateIntoTableDatabase' not implemented")

        def deleteIntoTableDatabase(self, paTableName, paId, current=None):
            raise NotImplementedError("servant method 'deleteIntoTableDatabase' not implemented")

        def getFromTableDatabaseGeneral(self, paTableName, paStartValue, paMaxValue, current=None):
            raise NotImplementedError("servant method 'getFromTableDatabaseGeneral' not implemented")

        def getFromTableDatbaseByProperty(self, paTableName, paStartValue, paMaxValue, paProperties, paValue, paTypeValue, paLogExp, current=None):
            raise NotImplementedError("servant method 'getFromTableDatbaseByProperty' not implemented")

        def getFromTableDatabaseById(self, paTableName, paId, paProperties, current=None):
            raise NotImplementedError("servant method 'getFromTableDatabaseById' not implemented")

        def getAllTablesFromDatabase(self, current=None):
            raise NotImplementedError("servant method 'getAllTablesFromDatabase' not implemented")

        def getAllMethodsFromTable(self, paTable, current=None):
            raise NotImplementedError("servant method 'getAllMethodsFromTable' not implemented")

        def getAllPropertiesFromTable(self, paTable, current=None):
            raise NotImplementedError("servant method 'getAllPropertiesFromTable' not implemented")

        def giveWorkstationClientInfo(self, paWorkstationName, paPercentageMemUsage, paPercentageDiskUsage, paPercentageCpuUsage, current=None):
            raise NotImplementedError("servant method 'giveWorkstationClientInfo' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_UVServerAppServer._t_ServerAppServerDisp)

        __repr__ = __str__

    _M_UVServerAppServer._t_ServerAppServerDisp = IcePy.defineClass('::UVServerAppServer::ServerAppServer', ServerAppServer, (), None, ())
    ServerAppServer._ice_type = _M_UVServerAppServer._t_ServerAppServerDisp

    ServerAppServer._op_Ping = IcePy.Operation('Ping', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), ((), IcePy._t_bool, False, 0), ())
    ServerAppServer._op_Shutdown = IcePy.Operation('Shutdown', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), None, ())
    ServerAppServer._op_insertIntoTableDatabase = IcePy.Operation('insertIntoTableDatabase', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), _M_UVServerAppServer._t_tyStringSequence, False, 0), ((), _M_UVServerAppServer._t_tyStringSequence, False, 0), ((), _M_UVServerAppServer._t_tyStringSequence, False, 0)), (((), IcePy._t_string, False, 0),), ((), IcePy._t_bool, False, 0), ())
    ServerAppServer._op_updateIntoTableDatabase = IcePy.Operation('updateIntoTableDatabase', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), _M_UVServerAppServer._t_tyStringSequence, False, 0), ((), _M_UVServerAppServer._t_tyStringSequence, False, 0), ((), _M_UVServerAppServer._t_tyStringSequence, False, 0)), (((), IcePy._t_string, False, 0),), ((), IcePy._t_bool, False, 0), ())
    ServerAppServer._op_deleteIntoTableDatabase = IcePy.Operation('deleteIntoTableDatabase', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0)), (((), IcePy._t_string, False, 0),), ((), IcePy._t_bool, False, 0), ())
    ServerAppServer._op_getFromTableDatabaseGeneral = IcePy.Operation('getFromTableDatabaseGeneral', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0)), (((), _M_UVServerAppServer._t_tyStringSequence, False, 0), ((), _M_UVServerAppServer._t_tyStringSequence, False, 0), ((), IcePy._t_string, False, 0)), ((), IcePy._t_bool, False, 0), ())
    ServerAppServer._op_getFromTableDatbaseByProperty = IcePy.Operation('getFromTableDatbaseByProperty', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), _M_UVServerAppServer._t_tyStringSequence, False, 0), ((), _M_UVServerAppServer._t_tyStringSequence, False, 0), ((), _M_UVServerAppServer._t_tyStringSequence, False, 0), ((), _M_UVServerAppServer._t_tyStringSequence, False, 0)), (((), _M_UVServerAppServer._t_tyStringSequence, False, 0), ((), IcePy._t_string, False, 0)), ((), IcePy._t_bool, False, 0), ())
    ServerAppServer._op_getFromTableDatabaseById = IcePy.Operation('getFromTableDatabaseById', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), _M_UVServerAppServer._t_tyStringSequence, False, 0)), (((), _M_UVServerAppServer._t_tyStringSequence, False, 0), ((), IcePy._t_string, False, 0)), ((), IcePy._t_bool, False, 0), ())
    ServerAppServer._op_getAllTablesFromDatabase = IcePy.Operation('getAllTablesFromDatabase', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (((), _M_UVServerAppServer._t_tyStringSequence, False, 0), ((), IcePy._t_string, False, 0)), ((), IcePy._t_bool, False, 0), ())
    ServerAppServer._op_getAllMethodsFromTable = IcePy.Operation('getAllMethodsFromTable', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0),), (((), _M_UVServerAppServer._t_tyStringSequence, False, 0), ((), _M_UVServerAppServer._t_tyStringSequence, False, 0), ((), _M_UVServerAppServer._t_tyStringSequence, False, 0), ((), _M_UVServerAppServer._t_tyStringSequence, False, 0), ((), _M_UVServerAppServer._t_tyStringSequence, False, 0), ((), IcePy._t_string, False, 0)), ((), IcePy._t_bool, False, 0), ())
    ServerAppServer._op_getAllPropertiesFromTable = IcePy.Operation('getAllPropertiesFromTable', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0),), (((), _M_UVServerAppServer._t_tyStringSequence, False, 0), ((), _M_UVServerAppServer._t_tyStringSequence, False, 0), ((), _M_UVServerAppServer._t_tyStringSequence, False, 0), ((), _M_UVServerAppServer._t_tyStringSequence, False, 0), ((), _M_UVServerAppServer._t_tyStringSequence, False, 0), ((), IcePy._t_string, False, 0)), ((), IcePy._t_bool, False, 0), ())
    ServerAppServer._op_giveWorkstationClientInfo = IcePy.Operation('giveWorkstationClientInfo', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0)), (((), IcePy._t_string, False, 0),), ((), IcePy._t_bool, False, 0), ())

    _M_UVServerAppServer.ServerAppServer = ServerAppServer
    del ServerAppServer

# End of module UVServerAppServer
